### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by naveencsemits** [WebDevSimplified/Mybrary#1]
C:\Users\ASHU\Desktop\Office node projects\Test\node_modules\dotenv\lib\main.js:41
  src.toString().split(NEWLINE).forEach(function (line, idx) {
      ^

TypeError: Cannot read property 'toString' of undefined
    at Object.parse (C:\Users\ASHU\Desktop\Office node projects\Test\node_modules\dotenv\lib\main.js:41:7)
    at Object.<anonymous> (C:\Users\ASHU\Desktop\Office node projects\Test\server.js:3:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

i am facing this error please someone help me i have already replaced the .load() to .parse()

**Comment by iamchaitanya** [comment]
I'm also getting same problem, did u solve it

**Comment by iamchaitanya** [comment]
try config()

**Comment by sachasmart** [comment]
Hate to be that guy but this keeps popping up. Have changed .load to .config with no luck

/Users/sachasmart/database/node_modules/mongoose/lib/connection.js:579
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^    

Error [MongooseError]: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at new MongooseError (/Users/ss/database/node_modules/mongoose/lib/error/mongooseError.js:10:11)
    at NativeConnection.Connection.openUri (/Users/ss/database/node_modules/mongoose/lib/connection.js:579:11)
    at Mongoose.connect (/Users/ss/database/node_modules/mongoose/lib/index.js:333:15)
    at Object.<anonymous> (/Users/ss/database/server.js:18:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  message: 'The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.',
  name: 'MongooseError'

**Comment by leon-99** [comment]
> try config()

Thank you.

**Comment by Younick05** [comment]
> > try config()
> 
> Thank you.


I am also facing the same problem. As you said to try config(), it only resolved the first problem but this mongoose problem is not getting resolve by using config().

**Comment by elvisisvan** [comment]
> try config()

thanks but i tried it and these showed up, any other suggestions? is it because i install the dependencies to the wrong place? using yarn v1.22.18 btw
https://youtu.be/qj2oDkvc4dQ

![image](https://user-images.githubusercontent.com/69122770/174488139-13a68b08-f46c-45ad-b4f1-cecb56f20add.png)
![image](https://user-images.githubusercontent.com/69122770/174488353-ac5f686c-e133-4ba3-98b4-e41389e05a3a.png)
![image](https://user-images.githubusercontent.com/69122770/174488391-a9c0f0fd-c35e-4428-ad23-e37dab978ed0.png)
as the error prompted, there's an error as line 12 of main.js file inside dotenv/lib folder but i dont know how to resolve it

**Comment by abdulmuqsit10101** [comment]
I replaced require('dotenv').load() with  require('dotenv').config() and it worked. Thank You

**Comment by ANIKETROY11005** [comment]
Thanks

**Comment by case-2** [comment]
MongooseServerSelectionError: connect ECONNREFUSED ::1:27017

Above error can be fixed by using "DATABASE_URL = mongodb://127.0.0.1:27017/mybrary" in the .env file as of 21 feb 2023

**Comment by devbhartra** [comment]
Assuming you're here from the Webdevsimplified video, he doesn't explicitly mention to start Mongo before hand, so make sure you open a new terminal, run ```brew services restart mongodb-community``` if you're on Mac (or use the respective command to restart the mongo service for your OS). 

I also changed the env file to have ```DATABASE_URL = "mongodb://0.0.0.0:27017/mybrary"```.
